### ISSUE TITLE
The target URL doesn't work on MTURK Notify Workers

### ISSUE THREAD

**Issue by hubertusputu1** [empiricaly/recruitment#8]
<img width="276" alt="Screen Shot 2020-11-18 at 16 41 59" src="https://user-images.githubusercontent.com/30768964/99506495-228a9f80-29bd-11eb-97a1-1adf17b7d967.png">

**Comment by npaton** [comment]
Note, the format changed to {{url}}, as we're now using Handlebars (https://handlebarsjs.com/guide/expressions.html#changing-the-context).

**Comment by hubertusputu1** [comment]
Sorry my bad, so should we implement the same thing on the message step as well? Because i tested it with {{url}} it wont' work, but worked on {url}.

**Comment by npaton** [comment]
Ah, yes! Message step has not been converted to handlebars yet. Please go ahead and convert message step.
